name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t containers07 .

      - name: Run tests
        run: docker run -v $(pwd)/tests:/var/www/html/tests containers07 php /var/www/html/tests/test.php
